server:
  port: 9090

spring:
  application:
    name: grab-api-gateway
  config:
    activate:
      on-profile: default

jwt:
  secret: ${JWT_SECRET}

authServiceUrl: ${AUTH_SERVICE_URL}
userServiceUrl: ${USER_SERVICE_URL}