server:
  port: 9090

spring:
  application:
    name: grab-api-gateway
  config:
    activate:
      on-profile: dev

jwt:
  secret: ${JWT_SECRET}

authServiceUrl: ${AUTH_SERVICE_URL}
userServiceUrl: ${USER_SERVICE_URL}

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10         # set to 200 in production
        failureRateThreshold: 50       # Open circuit if 50% requests fail
        slowCallRateThreshold: 50      # Consider slow calls as failures if 50% exceed threshold
        slowCallDurationThreshold: 2s  # 3s in production
        waitDurationInOpenState: 5s    # 20s in production
        permittedNumberOfCallsInHalfOpenState: 2  # 10 in production
        minimumNumberOfCalls: 5        # 50 in production
        automaticTransitionFromOpenToHalfOpenEnabled: true # Auto transition

      userCircuitBreaker:
        slidingWindowSize: 10           # set to 200 in production
        failureRateThreshold: 50        # Open circuit if 50% requests fail
        slowCallRateThreshold: 50       # Consider slow calls as failures if 50% exceed threshold
        slowCallDurationThreshold: 2s   # 3s in production
        waitDurationInOpenState: 5s     # 20s in production
        permittedNumberOfCallsInHalfOpenState: 2    # 10 in production
        minimumNumberOfCalls: 5         # 50 in production
        automaticTransitionFromOpenToHalfOpenEnabled: true  # Auto transition