apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grab-api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grab-api-gateway
    spec:
      containers:
        - image: ervincode/grabcar-api-gateway:${IMAGE_TAG}
          imagePullPolicy: Always
          name: grabcar-api-gateway
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_API_GATEWAY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: grab-urls
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: grab-urls
                  key: USER_SERVICE_URL

---
#services
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-car
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: grab-api-gateway
  sessionAffinity: None
  type: LoadBalancer