apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grab-api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grab-api-gateway
    spec:
      containers:
        - image: ervincode/grabcar-api-gateway:latest
          imagePullPolicy: IfNotPresent
          name: grab-api-gateway
          ports:
            - containerPort: 9090
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD

---
#services
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-api-gateway
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: grab-api-gateway
  sessionAffinity: None
  type: LoadBalancer