apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-car
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grab-api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grab-api-gateway
    spec:
      containers:
        - image: ervincode/grabcar-api-gateway:latest
          imagePullPolicy: IfNotPresent
          name: grabcar-api-gateway
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_API_GATEWAY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              port: 9090
              path: /actuator/health/readiness
            livelinessProbe:
              httpGet:
                port: 9090
                path: /actuator/health/liveliness
            restartPolicy: Always

---
#services
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grab-api-gateway
  name: grab-api-gateway
  namespace: grab-car
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: grab-api-gateway
  sessionAffinity: None
  type: LoadBalancer